[[website]]
name = "dm.noa.re"
namespace = "digital-membership"
external-secret = "/keys"
[website.config]
"/config/digital-membership.toml" = "digital-membership.toml"
"/config/wallet-cert.pem" = "wallet-cert.pem"
